services:
  web:
    build: .
    command: gunicorn catalog_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - dbdata:/app/dbdata
    expose:
      - "8000"
    environment:
      - DEBUG=1

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  dbdata:
