# Generated by Django 5.2 on 2025-04-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=50,
                                          unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('article', models.CharField(max_length=100,
                                             unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('wireless', models.BooleanField()),
                ('impedance', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField(blank=True,
                                                       null=True)),
                ('color', models.CharField(max_length=50)),
                ('form_factor',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='headphones.formfactor')),
            ],
        ),
    ]
