# Generated by Django 5.2.1 on 2025-05-18 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headphones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='headphones',
            name='price',
            field=models.DecimalField(decimal_places=2,
                                      default=1000,
                                      max_digits=10),
        ),
        migrations.AddField(
            model_name='headphones',
            name='price_big_wholesale',
            field=models.DecimalField(decimal_places=2,
                                      default=800,
                                      max_digits=10),
        ),
        migrations.AddField(
            model_name='headphones',
            name='price_small_wholesale',
            field=models.DecimalField(decimal_places=2,
                                      default=900,
                                      max_digits=10),
        ),
        migrations.AddField(
            model_name='headphones',
            name='qty_big_wholesale',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='headphones',
            name='qty_small_wholesale',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted', models.BooleanField(default=False)),
                ('manager',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='orders',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('headphones',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='headphones.headphones')),
                ('order',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='items', to='headphones.order')),
            ],
        ),
    ]
