# Generated by Django 5.2.1 on 2025-05-18 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headphones',
         '0002_headphones_price_headphones_price_big_wholesale_and_more'),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='headphones',
        ),
        migrations.RemoveField(
            model_name='headphones',
            name='price_big_wholesale',
        ),
        migrations.RemoveField(
            model_name='headphones',
            name='price_small_wholesale',
        ),
        migrations.RemoveField(
            model_name='headphones',
            name='qty_big_wholesale',
        ),
        migrations.RemoveField(
            model_name='headphones',
            name='qty_small_wholesale',
        ),
        migrations.AddField(
            model_name='headphones',
            name='wholesale_price_big',
            field=models.DecimalField(decimal_places=2,
                                      default=0, max_digits=10,
                                      verbose_name='Крупный опт'),
        ),
        migrations.AddField(
            model_name='headphones',
            name='wholesale_price_small',
            field=models.DecimalField(decimal_places=2,
                                      default=0, max_digits=10,
                                      verbose_name='Мелкий опт'),
        ),
        migrations.AddField(
            model_name='headphones',
            name='wholesale_qty_big',
            field=models.PositiveIntegerField(default=0,
                                              verbose_name='Кол-во для крупного опта'),
        ),
        migrations.AddField(
            model_name='headphones',
            name='wholesale_qty_small',
            field=models.PositiveIntegerField(default=0,
                                              verbose_name='Кол-во для мелкого опта'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='price',
            field=models.DecimalField(decimal_places=2,
                                      max_digits=10,
                                      verbose_name='Цена за штуку'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='items', to='headphones.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='headphones.headphones')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
